before:
  hooks:

builds:
  - id: aserto-idp-plugin-auth0
    main: ./cmd/aserto-idp-plugin-auth0
    binary: aserto-idp-plugin-auth0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s
      - -w
      - -X github.com/aserto-dev/aserto-idp-plugin-auth0/pkg/config.ver={{.Version}}
      - -X github.com/aserto-dev/aserto-idp-plugin-auth0/pkg/config.commit={{.ShortCommit}}
      - -X github.com/aserto-dev/aserto-idp-plugin-auth0/pkg/config.date={{.Date}}
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - format: zip
    rlcp: true
    files:
      - LICENSE
      - README.md
    name_template: >-
      aserto-idp-plugin-auth0{{ .Version }}_{{ .Os }}_{{- if eq .Arch "amd64" }}x86_64{{- else }}{{ .Arch }}{{ end }}

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

blobs:
  - provider: gs
    bucket: aserto-idp-cli
    folder: "plugins/aserto-idp-plugin-auth0/{{ .Major }}/{{ .Version }}"

release:
  github:
    owner: aserto-dev
    name: aserto-idp-plugin-auth0

  draft: false
  prerelease: false
  name_template: "aserto-idp-plugin-auth0 {{.Tag}}"